### ISSUE TITLE
inventory.sample

### ISSUE THREAD

**Issue by omps** [redhat-performance/satellite-monitoring#27]
Couldn't find inventory.sample in ("ansible/inventory.sample")

**Comment by h4xr** [comment]
@omps Updated the README with the correct filename for inventory. Thanks for pointing the typo :)

**Comment by omps** [comment]
the error is here.
  # cp conf/hosts.ini.sample conf/hosts.in

should it not be.
cp conf/hosts.ini.sample ansible/hosts.ini

moreover there is no inventory file. which has to be copied.

**Comment by h4xr** [comment]
No,
The hosts.sample.ini file should be copied to conf/hosts.ini only.

This hosts.ini acts as an inventory file for the playbooks. To use it, you can run ansible-playbook -i conf/hosts.ini <path to playbook>
