### ISSUE TITLE
Getting error with yum_repository

### ISSUE THREAD

**Issue by omps** [redhat-performance/satellite-monitoring#28]
getting the below error

    ERROR: yum_repository is not a legal parameter in an Ansible task or handler

do we need to have any specific version of ansible to be installed. I am running.
```
 (master)$ ansible --version
ansible 1.9.1
  configured module search path = None
```

**Comment by h4xr** [comment]
@omps Yes. The module ships with Ansible version 2.1 and above.
Thanks a lot for pointing this out :)
