### ISSUE TITLE
No graphs being displayed in dashboard

### ISSUE THREAD

**Issue by omps** [redhat-performance/satellite-monitoring#30]
Hi,

Able to install the collectd in satellite and capsule and graphite, grafana on the monitoring server. I am not able to see any graphs. Is there anything else i should be checking.

Could you please tell me how do you check if the collectd data is being collected or not.?

**Comment by h4xr** [comment]
@omps Did you run the dashboard-generic playbook under ansible.
The dashboard generic playbook is the one that installs the Dashboard on the grafana server.

Also, to validate if data is being reported to graphite or not from collectd, you can open http://<url to your graphite installation>:<port on which graphite is running (10009 by default)> and see if your satellite and capsule shows up there or not

**Comment by omps** [comment]
The data is being collected.

The issue it seems more for dashboard not creating.

At first was getting the error with invalid user while running the dashboard-generic ansible playbook.
'''
        "rc": 0,
        "start": "2017-07-28 06:47:31.432292",
        "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n
              Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --
:--:-- --:--:--     0\r100    31  100    31    0     0    395      0 --:--:-- --:--:-- --:--:--   397",
        "stdout": "{\"message\":\"Basic auth failed\"}",
        "stdout_lines": [
            "{\"message\":\"Basic auth failed\"}"
'''
FIXED THE ABOVE BY USING ADMIN:ADMIN and when manually ran the delete and create command

got the below with the create command.
'''
[{"classification":"DeserializationError","message":"invalid character '%' looking for beginning of object key string"},{"fieldNames":["Dashboard"],"classification":"RequiredError","message":"Required"}] 
'''

**Comment by h4xr** [comment]
@omps Thanks for pointing that issue out. Will fix that :)

As an workaround, you can also login to Grafana and upload the dashboard right there.
One additional step that you may need to take is to add the graphite as a datasource in your grafana.

You can do this using the Data sources tab located in the grafana after you login to grafana

**Comment by omps** [comment]
While manually importing the dashboard-generic template json template in grafana. 

getting this error.
JSON -> JS Serialization failed:
JSON.parse: expected property names or '}' at line 1 column 2 of the JSON data.

**Comment by omps** [comment]
Well finally made it working. The issue is with none of the graphite and grafana user details are correct. Creating admin user in graphite and setting up the admin password for the grafana helped solved the issue.

The user in graphite can be set as 
/usr/lib/python2.7/site-packages/graphite/manage.py createsuperuser

the path is beacause we are installing the graphite-web RPMS.

#
