### ISSUE TITLE
Cannot see how the elasticsearch is being used.

### ISSUE THREAD

**Issue by omps** [redhat-performance/satellite-monitoring#37]
I can see the yaml files for elk stack but cannot find this being used anywhere. Could you please suggest how you storing the collectd info. and where the elk stack is being used.

**Comment by h4xr** [comment]
@omps Sorry for the late reply.
We previously used to have elastic search, right now we are not using it. The playbooks are there for elk-stack and will be cleaned up soon.

Sorry for the confusion caused

**Comment by andreamtp** [comment]
Any update on the removal of ELK-stack cleanup?
