### ISSUE TITLE
Fix Dynflow worker names in config

### ISSUE THREAD

**Issue by jhutar** [redhat-performance/satellite-monitoring#53]
we need to add new Dynflow worker names to https://github.com/redhat-performance/satellite-monitoring/blob/18c28269c6e0c1b7db956721f65d768e97005298/ansible/roles/collectd-generic/templates/satellite6.collectd.conf.j2#L128-L130

**Comment by IshanSinghal** [comment]
Looks like already fixed by Imaan?
https://github.com/redhat-performance/satellite-monitoring/pull/52/files

**Comment by jhutar** [comment]
Even better :) Please just check there is nothing we are missing and close this :)

**Comment by jhutar** [comment]
Closing as per discussion with Ishan. Thank you!
